# Generated by Django 4.2.3 on 2024-03-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_yangiliklar_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songi_yillarda_bajarilgan_ishlar_xajmi',
            name='text1',
        ),
    ]
